app/controllers/contracts_controller.py
from flask import Blueprint, jsonify, current_app
import requests
import json
from app.db import get_db
from faker import Faker
import uuid
from datetime import datetime, timedelta
bp = Blueprint('contracts', __name__, url_prefix='/api')

@bp.route('/contracts', methods=['GET'])
def pullAllContracts():
    api_url = 'http://localhost:8080/contracts'  

    try:
        response = requests.get(api_url)

        if response.status_code == 200:
            contractsList = response.json()  
            insert_contracts_into_db(contractsList)  
        else:
            return jsonify({'error': 'Error al obtener contratos desde API REST'}), response.status_code

    except requests.exceptions.RequestException as e:
        return jsonify({'error': f'Error de conexión: {str(e)}'}), 500

    return jsonify(contractsList)

def insert_contracts_into_db(contractsList):
    db = get_db()
    cursor = db.cursor()
    
    for contract in contractsList:
        query = """
            INSERT INTO contracts (id, base_salary, contractType, employee, end_date, position, start_date, status)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
                base_salary = VALUES(base_salary),
                contractType = VALUES(contractType),
                employee = VALUES(employee),
                end_date = VALUES(end_date),
                position = VALUES(position),
                start_date = VALUES(start_date),
                status = VALUES(status)
        """
        contract_id = contract['id']
        base_salary = contract['base_salary']
        contractType = json.dumps(contract['contractType'])  # Convertir el diccionario a JSON
        employee = json.dumps(contract['employee'])  # Convertir el diccionario a JSON
        end_date = contract['end_date']
        position = json.dumps(contract['position'])  # Convertir el diccionario a JSON
        start_date = contract['start_date']
        status = contract['status']

        cursor.execute(query, (contract_id, base_salary, contractType, employee, end_date, position, start_date, status))
    
    db.commit()
    cursor.close()

@bp.route('/contracts/db', methods=['GET'])
def getAllContractsFromDB():
    db = get_db()
    cursor = db.cursor(dictionary=True)

    query = "SELECT * FROM contracts"
    cursor.execute(query)
    contracts = cursor.fetchall()

    for contract in contracts:
        contract['contractType'] = json.loads(contract['contractType'])
        contract['employee'] = json.loads(contract['employee'])
        contract['position'] = json.loads(contract['position'])

    cursor.close()

    return jsonify(contracts) 

@bp.route('/contracts/generate', methods=['POST'])
def generateContracts():
    fake = Faker()
    contractsList = []

    for _ in range(1000):
        contract_id = str(uuid.uuid4())
        start_date = fake.date_between(start_date='-1y', end_date='today')
        end_date = start_date + timedelta(days=365)
        base_salary = round(fake.random_number(digits=4), 2)
        status = fake.boolean()

        employee = {
            "id": str(uuid.uuid4()),
            "names": fake.first_name(),
            "last_names": fake.last_name(),
            "genre": fake.random_element(elements=('M', 'F')),
            "ci": fake.random_number(digits=8),
            "cellphone": fake.random_number(digits=9),
            "address": fake.address(),
            "birthdate": fake.date_of_birth(minimum_age=18, maximum_age=65).strftime('%Y-%m-%d'),
            "code": "EMP" + str(fake.random_number(digits=3)),
            "profession": {
                "id": str(uuid.uuid4()),
                "profession": fake.job()
            }
        }

        position = {
            "id": str(uuid.uuid4()),
            "position": fake.job(),
            "departmentBranch": {
                "id": str(uuid.uuid4()),
                "department": {
                    "id": str(uuid.uuid4()),
                    "department": fake.random_element(elements=('Contabilidad', 'IT', 'Ventas', 'Recursos Humanos'))
                },
                "branch": {
                    "id": str(uuid.uuid4()),
                    "branch": fake.random_element(elements=('Manzana 40 - Empresa', 'Sucursal Centro', 'Sucursal Norte'))
                }
            }
        }

        contract_type = {
            "id": str(uuid.uuid4()),
            "type": fake.random_element(elements=('Tiempo Completo', 'Medio Tiempo', 'Temporal'))
        }

        contract = {
            "id": contract_id,
            "base_salary": base_salary,
            "contractType": contract_type,
            "employee": employee,
            "end_date": end_date.strftime('%Y-%m-%d'),
            "position": position,
            "start_date": start_date.strftime('%Y-%m-%d'),
            "status": status
        }

        contractsList.append(contract)

    insert_contracts_into_db(contractsList)

    return jsonify({'message': '1000 contratos generados e insertados exitosamente.'}), 201

app/controllers/dashboard_controller.py
from flask import Blueprint, render_template
from app.controllers.contracts_controller import getAllContractsFromDB

dashboard_bp = Blueprint('dashboard', __name__, url_prefix='/dashboard')

@dashboard_bp.route('/gender', methods=['GET'])
def gender_dashboard():
    response = getAllContractsFromDB()
    contracts = response.get_json()
    employees_by_gender = {'Masculino': 0, 'Femenino': 0}
    for contract in contracts:
        genre = contract['employee']['genre']
        if genre == 'M':
            employees_by_gender['Masculino'] += 1
        elif genre == 'F':
            employees_by_gender['Femenino'] += 1
    
    return render_template('dashboard.html', employees_by_gender=employees_by_gender)

@dashboard_bp.route('/salary', methods=['GET'])
def salary_dashboard():
    response = getAllContractsFromDB()
    contracts = response.get_json()

    salary_by_contract_type = {}
    count_by_contract_type = {}

    for contract in contracts:
        contract_type = contract['contractType']['type']
        base_salary = float(contract['base_salary'])  

        if contract_type in salary_by_contract_type:
            salary_by_contract_type[contract_type] += base_salary
            count_by_contract_type[contract_type] += 1
        else:
            salary_by_contract_type[contract_type] = base_salary
            count_by_contract_type[contract_type] = 1

    average_salary_by_contract_type = {
        k: salary_by_contract_type[k] / count_by_contract_type[k]
        for k in salary_by_contract_type
    }
    return render_template('salary_dashboard.html', average_salary_by_contract_type=average_salary_by_contract_type)

@dashboard_bp.route('/professions', methods=['GET'])
def professions_dashboard():
    response = getAllContractsFromDB()
    contracts = response.get_json()

    # Calcular la cantidad de empleados por profesión
    employees_by_profession = {}

    for contract in contracts:
        profession = contract['employee']['profession']['profession']

        if profession in employees_by_profession:
            employees_by_profession[profession] += 1
        else:
            employees_by_profession[profession] = 1

    # Renderizar el template del dashboard con los datos obtenidos
    return render_template('professions_dashboard.html', employees_by_profession=employees_by_profession)

@dashboard_bp.route('/departments', methods=['GET'])
def department_dashboard():
    response = getAllContractsFromDB()
    contracts = response.get_json()

    # Calcular la cantidad de empleados por departamento
    employees_by_department = {}

    for contract in contracts:
        department = contract['position']['departmentBranch']['department']['department']

        if department in employees_by_department:
            employees_by_department[department] += 1
        else:
            employees_by_department[department] = 1

    # Renderizar el template del dashboard con los datos obtenidos
    return render_template('departments_dashboard.html', employees_by_department=employees_by_department)

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard - Empleados</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f4f4f9;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #4a90e2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        .chart-container {
            position: relative;
            height: 40vh;
            width: 100vh;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Empleados por Género</h1>
        <div class="chart-container">
            <canvas id="genderChart"></canvas>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const genderData = {{ employees_by_gender|tojson }};
            
            const ctx = document.getElementById('genderChart').getContext('2d');
            const genderChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: Object.keys(genderData),
                    datasets: [{
                        label: 'Cantidad de Empleados por Género',
                        data: Object.values(genderData),
                        backgroundColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    let label = context.label || '';
                                    if (label) {
                                        label += ': ';
                                    }
                                    if (context.parsed !== null) {
                                        label += context.parsed;
                                    }
                                    return label;
                                }
                            }
                        }
                    }
                }
            });
        });
    </script>
</body>
</html>

app/templates/departments_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard - Empleados por Departamento</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f4f4f9;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #4a90e2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        .chart-container {
            position: relative;
            height: 40vh;
            width: 100vh;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Empleados por Departamento</h1>
        <div class="chart-container">
            <canvas id="departmentsChart"></canvas>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const departmentsData = {{ employees_by_department|tojson }};
            
            const ctx = document.getElementById('departmentsChart').getContext('2d');
            const departmentsChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: Object.keys(departmentsData),
                    datasets: [{
                        label: 'Cantidad de Empleados por Departamento',
                        data: Object.values(departmentsData),
                        backgroundColor: 'rgba(218, 131, 27, 1)',
                        borderColor: 'rgba(218, 131, 27, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        x: {
                            beginAtZero: true
                        }
                    }
                }
            });
        });
    </script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bienvenido al Dashboard de Recursos Humanos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url('https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'); /* Imagen de fondo relacionada con RRHH */
            background-size: cover;
            background-position: center;
            color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
       .container {
            text-align: center;
            background-color: #fff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 600px;
            width: 100%;
        }
        h1 {
            color: #4a90e2;
        }
       .button {
            background-color: #4a90e2;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;
            margin: 10px;
        }
       .button:hover {
            background-color: #337ab7;
        }
        .button-down{
            background-color: #e24a4a;
            color: #fff;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;
            margin: 10px;
        }
       .button-down:hover {
            background-color: #b73333;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Dashboard de Recursos Humanos</h1>
        <p>Selecciona una página para continuar:</p>
        <button class="button" onclick="location.href='{{ url_for('dashboard.gender_dashboard') }}'">Empleados por Género</button>
        <button class="button" onclick="location.href='{{ url_for('dashboard.salary_dashboard') }}'">Salario por Tipo de Contrato</button>
        <button class="button" onclick="location.href='{{ url_for('dashboard.professions_dashboard') }}'">Empleados por Profesión</button>
        <button class="button" onclick="location.href='{{ url_for('dashboard.department_dashboard') }}'">Empleados por Departamento</button>
        <button class="button-down" onclick="pullContracts()">Bajar los últimos datos</button>
    </div>
    <script>
        function pullContracts() {
            fetch('{{ url_for('contracts.pullAllContracts') }}', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error('Error al obtener los contratos desde la API');
                }
                return response.json();
            })
            .then(data => {
                alert('Datos bajados exitosamente');
                console.log(data);
                // Puedes realizar acciones adicionales con los datos obtenidos si es necesario
            })
            .catch(error => {
                console.error('Error:', error);
                alert('Hubo un error al obtener los últimos datos desde la API');
            });
        }
    </script>
</body>
</html>

app/templates/professions_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard - Empleados por Profesión</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f4f4f9;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #4a90e2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        .chart-container {
            position: relative;
            height: 40vh;
            width: 100vh;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Empleados por Profesión</h1>
        <div class="chart-container">
            <canvas id="professionsChart"></canvas>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const professionsData = {{ employees_by_profession|tojson }};

            const ctx = document.getElementById('professionsChart').getContext('2d');
            const professionsChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: Object.keys(professionsData),
                    datasets: [{
                        label: 'Cantidad de Empleados por Profesión',
                        data: Object.values(professionsData),
                        backgroundColor: 'rgba(0, 104, 228, 1)',
                        borderColor: 'rgba(0, 104, 228, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    indexAxis: 'y',
                    scales: {
                        x: {
                            beginAtZero: true
                        }
                    }
                }
            });
        });
    </script>
</body>
</html>

app/templates/salary_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard - Salario </title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f4f4f9;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #4a90e2;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        .chart-container {
            position: relative;
            height: 40vh;
            width: 100vh;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Salario Base por Tipo de Contrato</h1>
        <div class="chart-container">
            <canvas id="salaryChart" width="400" height="400"></canvas>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const salaryData = {{ average_salary_by_contract_type|tojson }};
            
            const ctx = document.getElementById('salaryChart').getContext('2d');
            const salaryChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: Object.keys(salaryData),
                    datasets: [{
                        label: 'Salario Base Promedio',
                        data: Object.values(salaryData),
                        backgroundColor: 'rgba(0, 205, 93, 1)',
                        borderColor: 'rgba(0, 205, 93, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        });
    </script>
</body>
</html>